name: Build and Push Docker Image crawler

on:
  push:
    branches:
      - main
    paths:
      - "lambda-selenium-docker-crawler/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.crawler-buildx-cache
          key: crawler-buildx-cache
          restore-keys: crawler-buildx-

      - name: Create persistent Buildx builder
        run: |
          docker buildx create --name lambda-builder --use --bootstrap || echo "Builder already exists"

      - name: Build Docker image
        run: |
          docker buildx build \
            --builder lambda-builder \
            --platform linux/amd64 \
            --cache-from type=local,src=/tmp/.crawler-buildx-cache \
            --cache-to type=local,dest=/tmp/.crawler-buildx-cache \
            --output type=docker \
            -t crawler:build \
            ./lambda-selenium-docker-crawler

      - name: Tag Docker image
        run: |
          docker tag crawler:build ${{ steps.login-ecr.outputs.registry }}/crawler:latest

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/crawler:latest

      - name: Save Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.crawler-buildx-cache
          key: crawlers-buildx-cache

      - name: Update Lambda function to use new image
        run: |
          aws lambda update-function-code \
            --function-name crawler \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/crawler:latest
