name: Build and Push Docker Image for Lambda
on:
  push:
    branches:
      - main
    paths:
      - 'lambda-selenium-docker-scanner/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./lambda-selenium-docker-scanner
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/scanner:latest
          platforms: linux/amd64  # AWS Lambda가 지원하는 아키텍처 지정
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # Lambda 컨테이너 이미지 요구사항을 충족하도록 설정
          build-args: |
            LAMBDA_TASK_ROOT=/var/task
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      - name: Update Lambda function with new ECR image
        env:
          LAMBDA_FUNCTION_NAME: scanner
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: scanner
          IMAGE_TAG: latest
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --region ap-northeast-2
